# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PROJECT_NAME: ${{ github.event.repository.name }}

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      LDFLAGS: -s -w
      ARCH: amd64
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        goos: ["linux", "windows"]
        goarch: ["386", "amd64"]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Download dependencies
      run: go mod download

    - name: Build ${{ matrix.goos }}-${{ matrix.goarch }} binary
      run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -ldflags="$LDFLAGS"

    #- name: Test
    #  run: go test -v ./...
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PROJECT_NAME }}-${{ matrix.goos }}-${{ matrix.goarch }}
        path: ${{ env.PROJECT_NAME }}*
        if-no-files-found: error
        retention-days: 1
